---
title: "My research"
subtitle: "A small outline of my current research interests"
comments: false
---

::: callout-caution
## Work in progress

I am currently working on this page, please come back later.
:::

::: {.callout-note collapse="true" style="border-left-color: #16A2F3" appearance="minimal"}
## Bayesian discrete choice modeling
:::

::: {.callout-note collapse="true" style="border-left-color: #16A2F3" appearance="minimal"}
## Initializing numerical optimization
:::

::: {.callout-note collapse="true" style="border-left-color: #16A2F3" appearance="minimal"}
## Financial hidden Markov models

I am interested in modeling financial data with hidden Markov models (HMMs) - a versatile class of statistical models for time series data that is assumed to be dependent on latent states. In case of financial data, the latent states can be interpreted as different moods of the market. Even though these moods cannot be observed directly, price changes - which clearly depend on the current mood of the market - can be observed. Thereby, using an underlying Markov process, we can detect which mood is active at any point in time and how the different moods alternate. Depending on the current mood, a price change is generated by a different distribution. These distributions
:::